### ISSUE TITLE
Exception after Upgrade to 1.3.1.0 - Microsoft.Web.WebView2.WinForms - Could not load file or assembly.

### ISSUE THREAD

**Issue by oreleraki** [UE-Explorer/UE-Explorer#28]
This happen after upgrading my UE Explorer to 1.3.1.0

**Exception Details:**
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Web.WebView2.WinForms, Version=1.0.1462.37, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Web.WebView2.WinForms, Version=1.0.1462.37, Culture=neutral, PublicKeyToken=2a8ab48044d2601e'
   at UEExplorer.UI.Panels.WebViewPanel.InitializeComponent()
   at UEExplorer.UI.Tabs.UC_Default..ctor()

![image](https://user-images.githubusercontent.com/2606199/206107404-4b661db3-7c33-453d-a4f9-a8b36a069153.png)

**Comment by oreleraki** [comment]
Manually adding WebView2 dlls, solves this
```
Microsoft.Web.WebView2.Core.dll
Microsoft.Web.WebView2.Core.xml
Microsoft.Web.WebView2.WinForms.dll
Microsoft.Web.WebView2.WinForms.xml
Microsoft.Web.WebView2.Wpf.dll
Microsoft.Web.WebView2.Wpf.xml
```

**Comment by EliotVU** [comment]
Thanks! I've updated the files silently to address this issue.

Turns out this was caused by a last minute change to the Extensions output setup (you can see the missing files are installed under /Extensions/). Apparently the setup project gets confused by the circular dependencies and as a result the dependencies are skipped for the "UE Explorer.exe" assembly :/

I solved this by reverting back to hard-referencing the extension .dll files.
